### ISSUE TITLE
Only 95% Mastered can be completed

### ISSUE THREAD

**Issue by H4rry12** [koi-ikeno/hex-a-hop-per#1]
Following levels have a wrongly set par. 
Video from original game included to prove that par is too small.

Island - id: 34, par: 361
https://youtu.be/N87blUw7qoo

Maze - id: 50, par: 291
https://youtu.be/RK3uVYHmMKE

Deathtrap - id: 40, par: 187
https://youtu.be/kvk6jx8-KYo

Route finder - id: 62, par: 324
https://youtu.be/s5dJ8zU3SYQ

Branching Pathways - id: 27, par: 261
https://youtu.be/NFwjVrE1_XI

**Comment by koi-ikeno** [comment]
Thanks for reporting the issue. I found a bug in the calculation part of par and have fixed it😀

**Comment by H4rry12** [comment]
Fixed in version 1.9
